#Chinese (Simplified) Language default config translated by StarYunmeng
#https://www.spigotmc.org/members/staryunmeng.589461/
#Replace the original "config.yml" to use!

Database:
  #数据库储存类型 MYSQL 或 SQLITE
  Type: SQLITE
  MYSQL:
    Host: localhost
    Port: 3306
    Database: InteractionVisualizer
    Username: mysql
    Password: password
Messages:
  NoPermission: "&c您没有权限使用该命令!"
  Reload: "&aInteractionVisualizer重载成功!"
  Toggle:
    Usage: "&c用法: /interactionvisualizer toggle <itemstand/itemdrop/hologram>"
    Modes: "&c切换模式: itemstand, itemdrop, hologram"
    Console: "&c请提供玩家名称: /interactionvisualizer toggle <模式> [玩家名称]"
    ToggleOn: "&a切换至 %s 开启"
    ToggleOff: "&e切换至 %s 关闭"
    PlayerNotFound: "&c玩家并不在线！"

GarbageCollector:
  # 插件应该多久清除一次并删除不再需要跟踪的tile，方块或实体
  # 以 ticks 为度量, 20 ticks = 1秒
  # 当您的服务器无法处理过快的更新时调整此数据值
  Period: 600

TileEntityUpdate:
  # 自上次检查以来，插件应该多快收集tile实体的变化
  # 该插件将首先收集所有活跃区块 (以玩家为中心的 3x3 区块)
  # 然后在异步中加载这些区块中的所有tile实体
  # 需要注意的是影响的周期不只是 ChunksPerTick, 处理其他事情要比这个时间长几个 ticks
  # 当服务器无法应付高频更新时调整此值
  ChunksPerTick: 4
  # 当您遇到问题时再调整此值至 false
  LoadTileEntitiesAsync: true

LightUpdate:
  # 插件应多久更新一次需要使用的方块的光照水平
  # 以 ticks 为度量， 20 ticks = 1秒
  # 当您的服务器无法处理过快的照明更新时调整此数据值
  Period: 10

# 为这些方块启用 InteractionVisualizer
Blocks:
  Anvil:
    Enabled: true
  Beacon:
    Enabled: true
    # 插件应该多久检查一次方块更新
    # 以 ticks 为度量， 20 ticks = 1秒
    # 根据服务器实际性能情况调整这个值
    CheckingPeriod: 20
  BeeHive:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BeeNest:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BlastFurnace:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  BrewingStand:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&6"
      NoFuelColor: "&c"
      ProgressBarLength: 10
  CartographyTable:
    Enabled: true
  Chest:
    Enabled: true
  CraftingTable:
    Enabled: true
  Dispenser:
    Enabled: true
  DoubleChest:
    Enabled: true
  Dropper:
    Enabled: true
  EnchantmentTable:
    Enabled: true
  EnderChest:
    Enabled: true
  Furnace:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  Grindstone:
    Enabled: true
  Hopper:
    Enabled: true
  JukeBox:
    Enabled: true
    CheckingPeriod: 20
  Loom:
    Enabled: true
  NoteBlock:
    Enabled: true
  SmithingTable:
    Enabled: true
  Smoker:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  Stonecutter:
    Enabled: true
  ShulkerBox:
    Enabled: true

Entities:
  Villager: 
    Enabled: true

#为 InteractionVisualizer 启动的显示模块
#ItemStand 表示使用 盔甲架 和 物品展示框 的显示方式
#ItemDrop 表示使用 掉落物 的显示方式
#Hologram 表示使用 盔甲架 进行全息展示
Modules:
  ItemStand:
    Enabled: true
  ItemDrop:
    Enabled: true
  Hologram:
    Enabled: true

Settings:
  UseHandSwingAnimation: true
  PickupAnimationPlayerYOffset: 0
  DisabledWorlds: []
  
#由于中国网络的特殊性，建议关闭更新
Options:
  Updater: false
